// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPfgEFWCfREuq2fDO6pwXxoSnzHoewEaw',
    appId: '1:583518592360:web:841a7fb2d2f3a1837e4add',
    messagingSenderId: '583518592360',
    projectId: 'disacare-4aa7e',
    authDomain: 'disacare-4aa7e.firebaseapp.com',
    storageBucket: 'disacare-4aa7e.appspot.com',
    measurementId: 'G-5KRECBE5L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo2-i8RhPolUTDERuu0Rk8xWOqCzNT-PQ',
    appId: '1:583518592360:android:c7b5d3fdafbcd0297e4add',
    messagingSenderId: '583518592360',
    projectId: 'disacare-4aa7e',
    storageBucket: 'disacare-4aa7e.appspot.com',
  );
}
